version: "3"
services:
  mysql-standalone:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springbatchjob_db
      - MYSQL_USER=batchjob_sys
      - MYSQL_PASSWORD=12345
    image: mysql
    ports:
      - 3306:3306
  web:
    depends_on:
      - mysql-standalone
    build:
      context: ./
      dockerfile: Dockerfile
    image: batchjob
    ports:
      - 8888:8888
